import { nanoid } from 'nanoid';

export const leagueSeed = [
  {
    name: 'Monday Night League',
    description: 'Casual weekly league for friends and colleagues',
    access: 'public',
    numPlayers: 12,
    adminId: 1,
    startDate: '2025-01-01T00:50:30.765Z',
    endDate: '2025-12-31T23:59:59.765Z',
    contactFirstName: 'John',
    contactLastName: 'Smith',
    contactEmail: 'john.smith@example.com',
    contactPhone: '555-0101',
  },
  {
    name: 'Shooters Shoot',
    description: 'Competitive league with professional handicap system',
    access: 'public',
    numPlayers: 36,
    adminId: 1,
    startDate: '2025-02-01T00:50:30.765Z',
    endDate: '2025-12-31T23:59:59.765Z',
    contactFirstName: 'Michael',
    contactLastName: 'Johnson',
    contactEmail: 'michael.johnson@example.com',
    contactPhone: '555-0102',
  },
  {
    name: 'Sharpshooters',
    description: 'Invite-only elite tournament series',
    access: 'private',
    numPlayers: 20,
    adminId: 2,
    startDate: '2025-01-01T00:50:30.765Z',
    endDate: '2025-12-31T23:59:59.765Z',
    contactFirstName: 'Sarah',
    contactLastName: 'Williams',
    contactEmail: 'sarah.williams@example.com',
    contactPhone: '555-0103',
  },
  {
    name: 'Weekend Warriors',
    description: 'Saturday and Sunday tournament league',
    access: 'public',
    numPlayers: 24,
    adminId: 2,
    startDate: '2025-03-01T00:50:30.765Z',
    endDate: '2025-11-30T23:59:59.765Z',
    contactFirstName: 'Robert',
    contactLastName: 'Brown',
    contactEmail: 'robert.brown@example.com',
    contactPhone: '555-0104',
  },
  {
    name: 'Spring Classic',
    description: 'Spring season invitational league',
    access: 'private',
    numPlayers: 16,
    adminId: 1,
    startDate: '2025-03-01T00:50:30.765Z',
    endDate: '2025-05-31T23:59:59.765Z',
    contactFirstName: 'Elizabeth',
    contactLastName: 'Davis',
    contactEmail: 'elizabeth.davis@example.com',
    contactPhone: '555-0105',
  },
  {
    name: 'Corporate Cup',
    description: 'Inter-company golf tournament',
    access: 'private',
    numPlayers: 40,
    adminId: 1,
    startDate: '2025-04-01T00:50:30.765Z',
    endDate: '2025-08-31T23:59:59.765Z',
    contactFirstName: 'James',
    contactLastName: 'Miller',
    contactEmail: 'james.miller@example.com',
    contactPhone: '555-0106',
  },
  {
    name: 'Summer Scramble Series',
    description: 'Fun summer league with scramble and best-ball formats',
    access: 'public',
    numPlayers: 32,
    adminId: 2,
    startDate: '2025-06-01T00:50:30.765Z',
    endDate: '2025-08-31T23:59:59.765Z',
    contactFirstName: 'Patricia',
    contactLastName: 'Wilson',
    contactEmail: 'patricia.wilson@example.com',
    contactPhone: '555-0107',
  },
  {
    name: 'Fall Championship',
    description: 'Competitive fall season championship',
    access: 'public',
    numPlayers: 28,
    adminId: 2,
    startDate: '2025-09-01T00:50:30.765Z',
    endDate: '2025-11-30T23:59:59.765Z',
    contactFirstName: 'Christopher',
    contactLastName: 'Moore',
    contactEmail: 'christopher.moore@example.com',
    contactPhone: '555-0108',
  },
  {
    name: 'Twilight 9-Hole League',
    description: 'Quick evening 9-hole league',
    access: 'public',
    numPlayers: 16,
    adminId: 1,
    startDate: '2025-05-01T00:50:30.765Z',
    endDate: '2025-10-31T23:59:59.765Z',
    contactFirstName: 'Jennifer',
    contactLastName: 'Taylor',
    contactEmail: 'jennifer.taylor@example.com',
    contactPhone: '555-0109',
  },
  {
    name: 'Mixed Couples League',
    description: 'Couples tournament league',
    access: 'public',
    numPlayers: 20,
    adminId: 2,
    startDate: '2025-04-01T00:50:30.765Z',
    endDate: '2025-10-31T23:59:59.765Z',
    contactFirstName: 'Margaret',
    contactLastName: 'Anderson',
    contactEmail: 'margaret.anderson@example.com',
    contactPhone: '555-0110',
  },
];

export const eventSeed = [
  // Monday Night League - 18 weeks of events
  {
    leagueId: 1,
    courseId: 1,
    teeId: 1,
    name: 'Week 1 - January',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'front',
    scoringFormat: 'match',
    date: '2025-01-06T00:50:30.765Z',
    startTime: '17:00:00',
    interval: 10,
    status: 'completed',
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  {
    leagueId: 1,
    courseId: 2,
    teeId: 3,
    name: 'Week 2 - January',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'back',
    status: 'completed',
    date: '2025-01-13T00:50:30.765Z',
    startTime: '17:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  {
    leagueId: 1,
    courseId: 1,
    teeId: 2,
    name: 'Week 3 - January',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'front',
    status: 'completed',
    date: '2025-01-20T00:50:30.765Z',
    startTime: '17:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  {
    leagueId: 1,
    courseId: 3,
    teeId: 3,
    name: 'Week 4 - January',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'back',
    status: 'upcoming',
    date: '2025-01-27T00:50:30.765Z',
    startTime: '17:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  {
    leagueId: 1,
    courseId: 1,
    teeId: 1,
    name: 'Week 5 - February',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'front',
    status: 'upcoming',
    date: '2025-02-03T00:50:30.765Z',
    startTime: '17:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  // Shooters Shoot League - Sample events
  {
    leagueId: 2,
    courseId: 2,
    teeId: 3,
    name: 'Month 1 Tournament',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'front',
    status: 'completed',
    date: '2025-02-01T08:00:00.765Z',
    startTime: '08:00:00',
    scoringFormat: 'stroke',
    interval: 12,
    ptsPerHole: 0,
    ptsPerMatch: 0,
    ptsPerTeamWin: 5,
    strokePoints: JSON.stringify([15, 12, 10, 8, 6, 4, 2, 1]),
  },
  {
    leagueId: 2,
    courseId: 3,
    teeId: 3,
    name: 'Month 2 Tournament',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'back',
    status: 'upcoming',
    date: '2025-03-01T08:00:00.765Z',
    startTime: '08:00:00',
    scoringFormat: 'stroke',
    interval: 12,
    ptsPerHole: 0,
    ptsPerMatch: 0,
    ptsPerTeamWin: 5,
    strokePoints: JSON.stringify([15, 12, 10, 8, 6, 4, 2, 1]),
  },
  // Sharpshooters - Individual events
  {
    leagueId: 3,
    courseId: 1,
    teeId: 2,
    name: 'Championship Round 1',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'front',
    status: 'completed',
    date: '2025-01-15T09:00:00.765Z',
    startTime: '09:00:00',
    scoringFormat: 'stroke',
    interval: 10,
    ptsPerHole: 0,
    ptsPerMatch: 0,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 5, 4, 3, 2, 1]),
  },
  {
    leagueId: 3,
    courseId: 2,
    teeId: 3,
    name: 'Championship Round 2',
    eventCategory: 'round',
    eventFormat: 'individual',
    holes: 18,
    startSide: 'back',
    status: 'completed',
    date: '2025-02-15T09:00:00.765Z',
    startTime: '09:00:00',
    scoringFormat: 'stroke',
    interval: 10,
    ptsPerHole: 0,
    ptsPerMatch: 0,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 5, 4, 3, 2, 1]),
  },
  // Weekend Warriors
  {
    leagueId: 4,
    courseId: 3,
    teeId: 2,
    name: 'Saturday Tournament 1',
    eventCategory: 'round',
    eventFormat: 'team',
    holes: 18,
    startSide: 'front',
    status: 'completed',
    date: '2025-03-01T08:00:00.765Z',
    startTime: '08:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  {
    leagueId: 4,
    courseId: 1,
    teeId: 1,
    name: 'Sunday Tournament 1',
    eventCategory: 'round',
    eventFormat: 'team',
    holes: 18,
    startSide: 'back',
    status: 'upcoming',
    date: '2025-03-02T10:00:00.765Z',
    startTime: '10:00:00',
    scoringFormat: 'match',
    interval: 10,
    ptsPerHole: 1,
    ptsPerMatch: 1,
    ptsPerTeamWin: 1,
    strokePoints: JSON.stringify([10, 8, 6, 4, 2, 0]),
  },
  // Summer Scramble Series
  {
    leagueId: 7,
    courseId: 2,
    teeId: 2,
    name: 'June Scramble',
    eventCategory: 'round',
    eventFormat: 'team',
    holes: 18,
    startSide: 'front',
    status: 'upcoming',
    date: '2025-06-14T08:00:00.765Z',
    startTime: '08:00:00',
    scoringFormat: 'scramble',
    interval: 12,
    ptsPerHole: 0,
    ptsPerMatch: 1,
    ptsPerTeamWin: 2,
    strokePoints: JSON.stringify([12, 10, 8, 6, 4, 2]),
  },
  {
    leagueId: 7,
    courseId: 3,
    teeId: 2,
    name: 'July Best Ball',
    eventCategory: 'round',
    eventFormat: 'team',
    holes: 18,
    startSide: 'back',
    status: 'upcoming',
    date: '2025-07-12T08:00:00.765Z',
    startTime: '08:00:00',
    scoringFormat: 'bestball',
    interval: 12,
    ptsPerHole: 0,
    ptsPerMatch: 1,
    ptsPerTeamWin: 2,
    strokePoints: JSON.stringify([12, 10, 8, 6, 4, 2]),
  },
];

export const teamSeed = [
  // Monday Night League Teams
  {
    name: 'Hole In One Gang',
    leagueId: 1,
    seasonPoints: 24,
  },
  { name: 'Bogey Boys', leagueId: 1, seasonPoints: 18 },
  { name: 'Par For The Course', leagueId: 1, seasonPoints: 22 },
  { name: "Driver's Ed", leagueId: 1, seasonPoints: 16 },
  { name: 'Fairway Flyers', leagueId: 1, seasonPoints: 20 },
  { name: 'Rough Riders', leagueId: 1, seasonPoints: 14 },
  // Shooters Shoot League Teams
  { name: 'Eagle Eye', leagueId: 2, seasonPoints: 45 },
  { name: 'Birdie Bunch', leagueId: 2, seasonPoints: 38 },
  { name: 'Chip Masters', leagueId: 2, seasonPoints: 42 },
  { name: 'Putt Perfect', leagueId: 2, seasonPoints: 35 },
  { name: 'Stroke Kings', leagueId: 2, seasonPoints: 40 },
  { name: 'Green Machine', leagueId: 2, seasonPoints: 32 },
  { name: 'Fairway Kings', leagueId: 2, seasonPoints: 37 },
  { name: 'Sand Wedges', leagueId: 2, seasonPoints: 30 },
  // Weekend Warriors Teams
  { name: 'Saturday Soldiers', leagueId: 4, seasonPoints: 28 },
  { name: 'Sunday Best', leagueId: 4, seasonPoints: 25 },
  { name: 'Weekend Warriors', leagueId: 4, seasonPoints: 32 },
  { name: 'Tournament Titans', leagueId: 4, seasonPoints: 29 },
  { name: 'Victory Lane', leagueId: 4, seasonPoints: 26 },
  { name: 'Tee Time Legends', leagueId: 4, seasonPoints: 23 },
  // Summer Scramble Series Teams
  { name: 'Scramble Sensations', leagueId: 7, seasonPoints: 36 },
  { name: 'Best Ball Brothers', leagueId: 7, seasonPoints: 31 },
  { name: 'Foursome Friends', leagueId: 7, seasonPoints: 34 },
  { name: 'Team Awesome', leagueId: 7, seasonPoints: 28 },
  { name: 'Golf Gods', leagueId: 7, seasonPoints: 33 },
  { name: 'Swing Masters', leagueId: 7, seasonPoints: 27 },
  // Mixed Couples League Teams
  { name: 'Love & Golf', leagueId: 10, seasonPoints: 22 },
  { name: 'Couples Cup', leagueId: 10, seasonPoints: 19 },
  { name: 'Dynamic Duo', leagueId: 10, seasonPoints: 20 },
  { name: 'His & Hers', leagueId: 10, seasonPoints: 17 },
];

export const playerSeed = [
  // Monday Night League Players
  {
    firstName: 'Adam',
    lastName: 'Krieger',
    email: 'adam@gmail.com',
    handicap: 10,
    leagueId: 1,
    teamId: 1,
    seasonPoints: 12,
    type: 'player',
  },
  {
    firstName: 'Jim',
    lastName: 'User',
    email: 'jim@test.com',
    handicap: 9,
    leagueId: 1,
    teamId: 1,
    seasonPoints: 10,
    type: 'player',
  },
  {
    firstName: 'Dave',
    lastName: 'Smith',
    email: 'dave@gmail.com',
    handicap: 10,
    leagueId: 1,
    teamId: 2,
    seasonPoints: 8,
    type: 'player',
  },
  {
    firstName: 'Jeff',
    lastName: 'Wilson',
    email: 'jeff@test.com',
    handicap: 2,
    leagueId: 1,
    teamId: 2,
    seasonPoints: 6,
    type: 'player',
  },
  {
    firstName: 'Nandor',
    lastName: 'Flop',
    email: 'nandor@gmail.com',
    handicap: 10,
    leagueId: 1,
    teamId: 3,
    seasonPoints: 11,
    type: 'player',
  },
  {
    firstName: 'Nadia',
    lastName: 'Johnson',
    email: 'nadia@test.com',
    handicap: 14,
    leagueId: 1,
    teamId: 3,
    seasonPoints: 9,
    type: 'player',
  },
  {
    firstName: 'Lando',
    lastName: 'Smith',
    email: 'lando@gmail.com',
    handicap: 4,
    leagueId: 1,
    teamId: 4,
    seasonPoints: 7,
    type: 'player',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael@test.com',
    handicap: 7,
    leagueId: 1,
    teamId: 4,
    seasonPoints: 9,
    type: 'player',
  },
  {
    firstName: 'Sarah',
    lastName: 'Davis',
    email: 'sarah@gmail.com',
    handicap: 12,
    leagueId: 1,
    teamId: 5,
    seasonPoints: 10,
    type: 'player',
  },
  {
    firstName: 'Robert',
    lastName: 'Miller',
    email: 'robert@test.com',
    handicap: 8,
    leagueId: 1,
    teamId: 5,
    seasonPoints: 10,
    type: 'player',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Garcia',
    email: 'jennifer@gmail.com',
    handicap: 15,
    leagueId: 1,
    teamId: 6,
    seasonPoints: 7,
    type: 'player',
  },
  {
    firstName: 'Christopher',
    lastName: 'Martinez',
    email: 'chris@test.com',
    handicap: 6,
    leagueId: 1,
    teamId: 6,
    seasonPoints: 7,
    type: 'player',
  },
  // Shooters Shoot League Players
  {
    firstName: 'Tom',
    lastName: 'Anderson',
    email: 'tom@gmail.com',
    handicap: 3,
    leagueId: 2,
    teamId: 7,
    seasonPoints: 22,
    type: 'player',
  },
  {
    firstName: 'Lisa',
    lastName: 'Taylor',
    email: 'lisa@test.com',
    handicap: 8,
    leagueId: 2,
    teamId: 7,
    seasonPoints: 23,
    type: 'player',
  },
  {
    firstName: 'Mark',
    lastName: 'White',
    email: 'mark@gmail.com',
    handicap: 11,
    leagueId: 2,
    teamId: 8,
    seasonPoints: 18,
    type: 'player',
  },
  {
    firstName: 'Karen',
    lastName: 'Harris',
    email: 'karen@test.com',
    handicap: 13,
    leagueId: 2,
    teamId: 8,
    seasonPoints: 20,
    type: 'player',
  },
  {
    firstName: 'Peter',
    lastName: 'Clark',
    email: 'peter@gmail.com',
    handicap: 5,
    leagueId: 2,
    teamId: 9,
    seasonPoints: 21,
    type: 'player',
  },
  {
    firstName: 'Emily',
    lastName: 'Lewis',
    email: 'emily@test.com',
    handicap: 9,
    leagueId: 2,
    teamId: 9,
    seasonPoints: 21,
    type: 'player',
  },
  {
    firstName: 'James',
    lastName: 'Walker',
    email: 'james@gmail.com',
    handicap: 12,
    leagueId: 2,
    teamId: 10,
    seasonPoints: 17,
    type: 'player',
  },
  {
    firstName: 'Patricia',
    lastName: 'Hall',
    email: 'patricia@test.com',
    handicap: 11,
    leagueId: 2,
    teamId: 10,
    seasonPoints: 18,
    type: 'player',
  },
  {
    firstName: 'David',
    lastName: 'Jones',
    email: 'david@gmail.com',
    handicap: 7,
    leagueId: 2,
    teamId: 11,
    seasonPoints: 20,
    type: 'player',
  },
  {
    firstName: 'Linda',
    lastName: 'Young',
    email: 'linda@test.com',
    handicap: 14,
    leagueId: 2,
    teamId: 11,
    seasonPoints: 20,
    type: 'player',
  },
  {
    firstName: 'Richard',
    lastName: 'King',
    email: 'richard@gmail.com',
    handicap: 10,
    leagueId: 2,
    teamId: 12,
    seasonPoints: 16,
    type: 'player',
  },
  {
    firstName: 'Mary',
    lastName: 'Wright',
    email: 'mary@test.com',
    handicap: 12,
    leagueId: 2,
    teamId: 12,
    seasonPoints: 16,
    type: 'player',
  },
  // Sharpshooters Individual Players
  {
    firstName: 'Barry',
    lastName: 'Robinson',
    email: 'barry@gmail.com',
    handicap: 2,
    leagueId: 3,
    seasonPoints: 25,
    type: 'player',
  },
  {
    firstName: 'Susan',
    lastName: 'Scott',
    email: 'susan@test.com',
    handicap: 7,
    leagueId: 3,
    seasonPoints: 18,
    type: 'player',
  },
  {
    firstName: 'Steven',
    lastName: 'Green',
    email: 'steven@gmail.com',
    handicap: 5,
    leagueId: 3,
    seasonPoints: 22,
    type: 'player',
  },
  {
    firstName: 'Jessica',
    lastName: 'Adams',
    email: 'jessica@test.com',
    handicap: 11,
    leagueId: 3,
    seasonPoints: 15,
    type: 'player',
  },
  {
    firstName: 'Paul',
    lastName: 'Nelson',
    email: 'paul@gmail.com',
    handicap: 4,
    leagueId: 3,
    seasonPoints: 20,
    type: 'player',
  },
  // Weekend Warriors Players
  {
    firstName: 'Kevin',
    lastName: 'Carter',
    email: 'kevin@gmail.com',
    handicap: 6,
    leagueId: 4,
    teamId: 16,
    seasonPoints: 14,
    type: 'player',
  },
  {
    firstName: 'Nicole',
    lastName: 'Mitchell',
    email: 'nicole@test.com',
    handicap: 10,
    leagueId: 4,
    teamId: 16,
    seasonPoints: 14,
    type: 'player',
  },
  {
    firstName: 'Andrew',
    lastName: 'Perez',
    email: 'andrew@gmail.com',
    handicap: 8,
    leagueId: 4,
    teamId: 17,
    seasonPoints: 12,
    type: 'player',
  },
  {
    firstName: 'Ashley',
    lastName: 'Roberts',
    email: 'ashley@test.com',
    handicap: 12,
    leagueId: 4,
    teamId: 17,
    seasonPoints: 13,
    type: 'player',
  },
  // Summer Scramble Players
  {
    firstName: 'Brian',
    lastName: 'Phillips',
    email: 'brian@gmail.com',
    handicap: 9,
    leagueId: 7,
    teamId: 21,
    seasonPoints: 18,
    type: 'player',
  },
  {
    firstName: 'Amanda',
    lastName: 'Campbell',
    email: 'amanda@test.com',
    handicap: 13,
    leagueId: 7,
    teamId: 21,
    seasonPoints: 18,
    type: 'player',
  },
  {
    firstName: 'Ryan',
    lastName: 'Parker',
    email: 'ryan@gmail.com',
    handicap: 11,
    leagueId: 7,
    teamId: 22,
    seasonPoints: 15,
    type: 'player',
  },
  {
    firstName: 'Rachel',
    lastName: 'Evans',
    email: 'rachel@test.com',
    handicap: 14,
    leagueId: 7,
    teamId: 22,
    seasonPoints: 16,
    type: 'player',
  },
  // Mixed Couples Players
  {
    firstName: 'Jason',
    lastName: 'Edwards',
    email: 'jason@gmail.com',
    handicap: 7,
    leagueId: 10,
    teamId: 28,
    seasonPoints: 11,
    type: 'player',
  },
  {
    firstName: 'Victoria',
    lastName: 'Collins',
    email: 'victoria@test.com',
    handicap: 11,
    leagueId: 10,
    teamId: 28,
    seasonPoints: 11,
    type: 'player',
  },
  {
    firstName: 'Brandon',
    lastName: 'Stewart',
    email: 'brandon@gmail.com',
    handicap: 9,
    leagueId: 10,
    teamId: 29,
    seasonPoints: 9,
    type: 'player',
  },
  {
    firstName: 'Stephanie',
    lastName: 'Sanchez',
    email: 'stephanie@test.com',
    handicap: 12,
    leagueId: 10,
    teamId: 29,
    seasonPoints: 10,
    type: 'player',
  },
];
